name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Get
        run: |
             wget -O lspatch.jar https://github.com/LSPosed/LSPatch/releases/download/v0.5.1/lspatch.jar
             wget -O BiliRoaming.apk https://github.com/zjns/BiliRoamingX/releases/download/v1.6.8/BiliRoamingX-v1.6.8.apk
             wget -O bilibili.apk https://dl.hdslb.com/mobile/latest/android64/iBiliPlayer-bili.apk
      - name: Build
        run: |
            java -jar lspatch.jar bilibili.apk -m BiliRoaming.apk -o APK -l 2
      - uses: actions/upload-artifact@v3
        with:
          name: APK
          path: APK
      - name: Upload apk to release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref_name }}
          tag_name: release
          files: APK/*
